[book]
authors = ["Poulad Ashrafpour", "Aleksey Usatov", "karb0f0s", "Miha Zupan", "Wizou"]
multilingual = false
src = "src"
title = "A guide to Telegram.Bot library"
site-url = "https://telegrambots.github.io/book/"
language = "en"

[output.html]
git-repository-url = "https://github.com/TelegramBots/book"
additional-css = ["theme/custom.css"]

[output.html.fold]
enable = true
level = 1

[preprocessor.alerts]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html.redirect]
"Migration-Guide-to-Version-21.x.html" = "migrate/Version-21.x.html"
